name: CI — Cache Prime Example

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore npm cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-03e1cf5

      - name: Install dependencies
        run: npm ci

      - name: prime-cache-03e1cf5
        run: echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"

      - name: Run tests
        run: npm test
